cask_args appdir: '/Applications'

brew 'asdf'
brew 'bat'
brew 'coreutils'
brew 'curl'
brew 'fd'
brew 'gh'
brew 'git'
brew 'glab'
brew 'imagemagick'
brew 'jq'
brew 'neovim'
brew 'openssl'
brew 'qrencode'
brew 'readline'
brew 'shellcheck'
brew 'tig'
brew 'tmux'
brew 'wget'

cask '1password'
cask 'docker'
cask 'drawio'
cask 'firefox'
cask 'font-meslo-for-powerline'
cask 'font-source-code-pro'
cask 'google-chrome'
cask 'inkscape'
cask 'iterm2'
cask 'rectangle'
cask 'spotify'
cask 'visual-studio-code'
