# base16 color scheme (https://github.com/chriskempson/base16)
scheme: "Base"
author: "Paul Meinhardt (https://github.com/pmeinhardt)"
base00: "000000"
base01: "BDE077"
base02: "FFE863"
base03: "666666"
base04: "AACCBB"
base05: "DDDDDD"
base06: "E16A98"
base07: "CCCCCC"
base08: "E84F4F"
base09: "D23D3D"
base0A: "FEA63C"
base0B: "B7CE42"
base0C: "6D878D"
base0D: "66AABB"
base0E: "B7416E"
base0F: "42717B"
